### ISSUE TITLE
im can’t shoot

### ISSUE THREAD

**Issue by mr2meowsYT** [Slideshow776/Terfenstein-3D#4]
im clicker the enemie and they aren’t die it no work

**Comment by Slideshow776** [comment]
If you're playing the html version, that's old and just a crude demo.
If you're playing the desktop version, are you by chance standing in a doorway with a door?

**Comment by mr2meowsYT** [comment]
i player th hml vresion

**Comment by Slideshow776** [comment]
Well, the html version is just a laggy demo. But perhaps I do want to replace it with something more workable. Thank you for bringing this to my attention < 3

I'll put a note for it on the [kanban board](https://github.com/Slideshow776/Terfenstein-3D/projects/1).

**Comment by Slideshow776** [comment]
I've decided to discontinue HTML because it does not scale well with this graphic intense-ish game.
Also, I'm wanting to finish this game asap, and cutting out HTML makes that goal a bit easier.

I've yet to decide whether or not to sell this game or just release it for free.
For now, if you want to play it you have to download and compile it yourself, instructions on how to do so can be found elsewhere.

Thank you for your interest : )

sincerely,
